.\" Developed by the LUMI User Support Team  for the LUMI consortium.
.TH man 1 "DATE" "VERSION" "lumi-workspaces"

.SH NAME
lumi-workspaces \- Show quota on LUMI as obtained directly from Lustre.

.SH DESCRIPTION
\fBlumi-wokspaces\fR shows quota and allocations for the current user.

.SH OPTIONS

The current version of \fBlumi-workspaces\fR does not take any command line options.

.SH SEE ALSO
lumi-quota(1)

.SH AUTHOR
Developed by the LUMI User Support Team for the LUMI consortium
