.\" Developed by the LUMI User Support Team  for the LUMI consortium.
.TH man 1 "DATE" "VERSION" "lumi-quota"

.SH NAME
lumi-quota \- Show quota on LUMI as obtained directly from Lustre.

.SH DESCRIPTION
\fBlumi-quota\fR shows quota for the current user (including all active projects)
or a given project.

.SH OPTIONS
.TP
\fB-v\fR
Show more detailed output, including the soft and hard quota (columns Quota and Limit respectively)
.TP
\fB-p\fR
Show quota for the given project only. \fB-p\fR should be followed by a LUMI project number in the 
form \fBproject_46XXXXXXX\fR.

.SH SEE ALSO
lumi-workspaces(1), lumi-allocations(1)

.SH AUTHOR
Developed by the LUMI User Support Team for the LUMI consortium
