.\" Developed by the LUMI User Support Team  for the LUMI consortium.
.TH man 1 "DATE" "VERSION" "lumi-check-quota"

.SH NAME
\fBlumi-check-quota\fR \- Show warnings when running out of quota or allocations.

.SH DESCRIPTION
\fBlumi-check-quota\fR is a variant of the script that is run at login to show warnings
about directories running out of quota or projects running out of allocations.

.SH OPTIONS

The command currently does not accept any command line options.

.SH SEE ALSO
lumi-workspaces(1), lumi-quota(1), lumi-allocations(1)

.SH AUTHOR
Developed by the LUMI User Support Team for the LUMI consortium
