.\" Developed by the LUMI User Support Team  for the LUMI consortium.
.TH man 1 "DATE" "VERSION"  "lumi-tools-overview"

.SH NAME
\fBlumi-tools\fR \- Module bundling various tools that users can use to get information
about their account and projects.

.SH DESCRIPTION
\fBlumi-tools\fR contains various tools that users can use to get information
about their account and projects, e.g., current quota and remaining billing units.

Commands:
.TP
\fBlumi-workspaces\fR
Overall command for a user to quickly check all information about quota and allocations.
.TP
\fBlumi-quota\fR
Tool to get information about the quota for the current user or for a given project.
.TP
\fBlumi-allocations\fR
Tool to get information about the allocations for all projects of the current user or
for a given project.
.TP
\fBlumi-check-quota\fR
Command to show warnings when running out of quota or allocations, similar to the 
warnings shown at login.
.TP
\fBlumi-ldap-projectinfo\fR
Shows information about projects, including the last stored state of the allocations
and the quota. It does show more information than \fBlumi-workspaces\fR but less live
information. What you can see also depends on your privileges on the system.

.SH SEE ALSO
lumi-workspaces(1), lumi-quota(1), lummi-allocations(1), lumi-check-quota(1),
lumi-ldap-projectinfo(1)

.SH AUTHOR
Developed by the LUMI User Support Team for the LUMI consortium
